name: Deployment - Production (Prod Branch)

on:
  push:
    branches: [ "production" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        echo "PORT=${{ vars.PORT || 3000 }}" > .env
        echo "NODE_ENV=${{ vars.NODE_ENV || 'production' }}" >> .env
        echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> .env
        echo "GOOGLE_CALLBACK_URL=${{ vars.GOOGLE_CALLBACK_URL }}" >> .env
        echo "FACEBOOK_CALLBACK_URL=${{ vars.FACEBOOK_CALLBACK_URL }}" >> .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env


    - name: Build and Restart with Docker Compose
      run: |
        docker compose down
        docker compose up --build -d
        docker system prune -f
        sleep 10 # Wait for container to fully start
        docker exec market_watch_app sh -c "BCRYPT_SALT_ROUNDS=1 npm test"
